photos_project_v3
yuriichajka/photos_project pull request #3
Opened 2021-08-04 19:39 UTC by yuriichajka

2021-08-06 10:30 UTC, mike-gusiev requested changes

2021-08-06 10:30 UTC, mike-gusiev commented on README.md
>  The page will reload if you make edits.\
постав лоадер для картинки в попапі. бо вона пригає коли відкриває попап

2021-08-06 10:30 UTC, mike-gusiev commented on src/App.js
> +import Modal from './components/Modal';
в папці src/components створи файл index.js. щоб всі компоненти можна було імпортувати одним рядком

2021-08-06 10:30 UTC, mike-gusiev commented on src/App.js
> +
зайвий перенос рядка

2021-08-06 10:30 UTC, mike-gusiev commented on src/App.js
>      let [showModal, setShowModal] = useState(false);
змінні декларуй зверху функції

2021-08-06 10:30 UTC, mike-gusiev commented on src/App.js
> +                            photos.map(value => <Link to={'/photo/' + value.id}><Image item={value.url} key={value.id} onClick={openModal}/></Link>)
надто довга строка. вилізла за ліміт в 120 символів. поперенось на декілька рядків

2021-08-06 10:30 UTC, mike-gusiev commented on src/components/Image.js
> +const Image = ({ item, onClick }) => {
використовуй коротку форму es6 функцій без return, там де це 
ожливо

2021-08-06 10:30 UTC, mike-gusiev commented on src/components/Image.js
> +export default Image;
перед відправкою пул реквеста на рев'ю переглядай свій пул реквест. і виправиш все що помітиш самостійно, до того як мені відправляти на рев'ю.

якщо бачиш таку іконку, значить у цього файлу не вистачає переносу рядка в кінці.

2021-08-06 10:30 UTC, mike-gusiev commented on src/components/Modal.js
> +    let location = useLocation();
const має бути

2021-08-06 10:30 UTC, mike-gusiev commented on src/components/Modal.js
> +    console.log(location.pathname)
- не треба коммітити console.log i debugger. повидаляєш іх
- зайві переноси рядків знизу

2021-08-06 10:30 UTC, mike-gusiev commented on src/components/Modal.js
> +            { showModal ? (
використовую оператор && замість ?. тоді не доведеться null писати в кінці

2021-08-06 10:30 UTC, mike-gusiev commented on src/redux/reducer/reducer.js
> +const initialState = {
структура редаксу трохи неправильна. позбудься папки reducers. і створи папку src/redux/ducks. і туди в окремі файли помісти усі екшени/редюсери/саги і тд одним файлом. все що відноситься до одного duck - має бути в одному файлі:
https://github.com/erikras/ducks-modular-redux

2021-08-06 10:30 UTC, mike-gusiev commented on src/styled/styledModal.js
> +    background: rgba(0, 0, 0, 0.8);
створи файл для глобальних змінних styled components. і туди повиносили всі кольори і розміри в медіа запитах

2021-08-09 06:18 UTC, mike-gusiev requested changes

2021-08-09 06:18 UTC, mike-gusiev commented on src/App.js
> +import Modal from './components/Modal';
це ще не зроблено. ти styled components імпортишь однією строкоє, а компоненти все ще різними

2021-08-09 06:18 UTC, mike-gusiev commented on src/App.js
зайвий перенос рядка

2021-08-09 06:18 UTC, mike-gusiev commented on src/App.js
> +
це також не пофікшено

2021-08-09 06:18 UTC, mike-gusiev commented on src/App.js
> +                        {
порушені відступи та розміщення скобок. замість таких отступів:

```
{
    images.map(value =>
        <Link to={'/photo/' + value.id}>
            <Image item={value.url} key={value.id} onClick={openModal}/>
        </Link>)
}
```


використовую такі:
```
{images.map(value => (
    <Link to={'/photo/' + value.id}>
        <Image item={value.url} key={value.id} onClick={openModal} />
    </Link>
))}
```

2021-08-09 06:18 UTC, mike-gusiev commented on src/components/Image.js
> +export default Image;
не пофіксив перенос рядка

2021-08-09 06:18 UTC, mike-gusiev commented on src/components/Image.js
> +const Image = ({ item, onClick }) => <Img loading='lazy'
порушені відступи та розміщення скобок. замість таких отступів:

```
const Image = ({ item, onClick }) => <Img loading='lazy'
                                          width='300px'
                                          height='200px'
                                          src={ item }
                                          onClick={ onClick }/>
```


використовую такі:
```
const Image = ({ item, onClick }) => (
	<Img
		loading='lazy'
		width='300px'
		height='200px'
		src={ item }
		onClick={ onClick }
	/>
);
```

2021-08-09 06:18 UTC, mike-gusiev commented on src/components/Modal.js
> +import { Background, ModalWrapper, CloseModalButton, ModalContainer, Comments, Comment, ModalImg } from '../styled/styledModal'
- не має крапки з комою
- вийшов за ліміти рядка в 120 символів. перенеси на декілька рядків

2021-08-09 06:18 UTC, mike-gusiev commented on src/components/Modal.js
> +    const validations = yup.object().shape({
винось усі валідатори в окремий файл src/validators.js

2021-08-09 06:18 UTC, mike-gusiev commented on src/components/Modal.js
> +                                           {({ values,
неправильні відступи та переноси html тегів і параметрів функції

2021-08-09 06:18 UTC, mike-gusiev commented on src/components/Modal.js
> +export default Modal;
не добавив перенос рядка

2021-08-09 06:18 UTC, mike-gusiev commented on src/redux/sagas/handlers/images.js
> +import { call, put } from 'redux-saga/effects'
для саги не треба окремої папки створювати. вона має бути в даках. все в одному файлі має бути що відноситься до одного дака

2021-08-09 06:18 UTC, mike-gusiev commented on src/redux/sagas/requests/images.js
> +import axios from 'axios';
всі реквести мають бути в файле src/api.js

2021-08-09 06:18 UTC, mike-gusiev commented on src/redux/sagas/rootSaga.js
> +import { takeLatest } from 'redux-saga/effects'
рут сага має бути в папці src/redux

2021-08-09 06:18 UTC, mike-gusiev commented on src/services/api.js
> +import axios from 'axios';
всі ajax запити мають бути в файлі src/api.js. позбудься від папки services

2021-08-09 06:18 UTC, mike-gusiev commented on src/styled/styledModal.js
> +    background: rgba(0, 0, 0, 0.8);
це не зробив

2021-08-09 11:26 UTC, yuriichajka commented on src/App.js
done

2021-08-10 08:42 UTC, mike-gusiev requested changes

2021-08-10 08:42 UTC, mike-gusiev commented on src/App.js
> +                <Route exact path={'/photo/:id'} render={() => <Modal showModal={showModal}
сделай тут перенос строк такой же как и на строке 38

2021-08-10 08:42 UTC, mike-gusiev commented on src/api.js
> +        url: 'https://boiling-refuge-66454.herokuapp.com/images'
повыноси url в константы в этом файле

2021-08-10 08:42 UTC, mike-gusiev commented on src/components/Modal.js
> +import { Background, ModalWrapper,
вместо таких переносов:

```
import { Background, ModalWrapper,
    CloseModalButton, ModalContainer,
    Comments, Comment, ModalImg } from '../styled/styledModal';
```

делай такие:

```
import {
	Background, ModalWrapper, CloseModalButton, ModalContainer, Comments,
	Comment, ModalImg
} from '../styled/styledModal';
```

2021-08-10 08:42 UTC, mike-gusiev commented on src/components/Modal.js
> +    let [modalPhoto, setModalPhoto] = useState(false)
точек с запятой не хватает

2021-08-10 08:42 UTC, mike-gusiev commented on src/components/index.js
> +export {Modal, Image};
пробелов не хватает внутри скобок

2021-08-10 08:42 UTC, mike-gusiev commented on src/styled/styledPhotos.js
> +`;
перенос строки

2021-08-10 09:41 UTC, merged